apiVersion: v1
kind: Service
metadata:
  name: hermes-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: hermes-postgres
spec:
  selector:
    app: hermes-postgres
  ports:
    - port: 5432
      targetPort: 5432
