apiVersion: v1
kind: Secret
metadata:
  name: hermes-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: hermes-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: hermes-lab-change-me
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_DB: {{ .Values.postgres.database }}
