apiVersion: v1
kind: Service
metadata:
  name: hermes-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: hermes-redis
spec:
  selector:
    app: hermes-redis
  ports:
    - port: 6379
      targetPort: 6379
